CREATE WAREHOUSE OLIST_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE OLIST_WH;
 
SELECT CURRENT_WAREHOUSE();

CREATE DATABASE OLIST_DW;

USE DATABASE OLIST_DW;

CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS MART;


USE DATABASE OLIST_DW;
USE SCHEMA STAGING;

CREATE OR REPLACE STAGE OLIST_INTERNAL_STAGE;

SHOW STAGES;

CREATE OR REPLACE FILE FORMAT PARQUET_FORMAT
TYPE = PARQUET;

DROP TABLE OLIST_DW.STAGING.ORDERS;
