-- =========================================================
-- BUSINESS QUESTION 1
-- What is the total revenue generated by the marketplace?
-- =========================================================

SELECT
    ROUND(SUM(TOTAL_ORDER_VALUE),2) AS TOTAL_REVENUE
FROM OLIST_DW.MART.FACT_ORDERS;



-- =========================================================
-- BUSINESS QUESTION 2
-- How has revenue changed over time?
-- =========================================================

SELECT
    ORDER_YEAR,
    ORDER_MONTH,
    ROUND(SUM(TOTAL_ORDER_VALUE),2) AS REVENUE
FROM OLIST_DW.MART.FACT_ORDERS
GROUP BY
    ORDER_YEAR,
    ORDER_MONTH
ORDER BY
    ORDER_YEAR,
    ORDER_MONTH;


-- =========================================================
-- BUSINESS QUESTION 3
-- What is the Average Order Value (AOV)?
-- =========================================================

SELECT
    ROUND(AVG(TOTAL_ORDER_VALUE),2) AS AOV
FROM OLIST_DW.MART.FACT_ORDERS;



-- =========================================================
-- BUSINESS QUESTION 4
-- Which states generate the highest revenue?
-- =========================================================

SELECT
    dc.CUSTOMER_STATE,
    ROUND(SUM(fo.TOTAL_ORDER_VALUE),2) AS REVENUE
FROM OLIST_DW.MART.FACT_ORDERS fo
JOIN OLIST_DW.MART.DIM_CUSTOMERS dc
    ON fo.CUSTOMER_ID = dc.CUSTOMER_ID
GROUP BY dc.CUSTOMER_STATE
ORDER BY REVENUE DESC;



-- =========================================================
-- BUSINESS QUESTION 5
-- Which cities generate the highest revenue?
-- =========================================================

SELECT
    dc.CUSTOMER_CITY,
    ROUND(SUM(fo.TOTAL_ORDER_VALUE),2) AS REVENUE
FROM OLIST_DW.MART.FACT_ORDERS fo
JOIN OLIST_DW.MART.DIM_CUSTOMERS dc
    ON fo.CUSTOMER_ID = dc.CUSTOMER_ID
GROUP BY dc.CUSTOMER_CITY
ORDER BY REVENUE DESC
LIMIT 40;



-- =========================================================
-- BUSINESS QUESTION 6
-- Who are the most valuable customers?
-- =========================================================

WITH customer_revenue AS (
    SELECT
        c.CUSTOMER_UNIQUE_ID,
        SUM(f.TOTAL_ORDER_VALUE) AS revenue
    FROM OLIST_DW.MART.FACT_ORDERS f
    JOIN OLIST_DW.MART.DIM_CUSTOMERS c
        ON f.CUSTOMER_ID = c.CUSTOMER_ID
    GROUP BY c.CUSTOMER_UNIQUE_ID
)

SELECT *,
       DENSE_RANK() OVER (
           ORDER BY revenue DESC
       ) AS customer_rank
FROM customer_revenue;


-- =========================================================
-- BUSINESS QUESTION 7
-- How many customers place multiple orders?
-- =========================================================

SELECT
    COUNT(*) AS REPEAT_CUSTOMERS
FROM OLIST_DW.MART.CUSTOMER_METRICS
WHERE TOTAL_ORDERS > 1;


-- =========================================================
-- BUSINESS QUESTION 8
-- Which customers belong to high-value segments?
-- =========================================================

SELECT
    CUSTOMER_UNIQUE_ID,
    TOTAL_ORDERS,
    CUSTOMER_LIFETIME_VALUE,
    AVERAGE_ORDER_VALUE
FROM OLIST_DW.MART.CUSTOMER_METRICS
ORDER BY
    TOTAL_ORDERS DESC,
    CUSTOMER_LIFETIME_VALUE DESC;


    -- =========================================================
-- BUSINESS QUESTION 9
-- Which product categories generate the most revenue?
-- =========================================================

WITH category_revenue AS (
    SELECT
        dp.PRODUCT_CATEGORY_NAME,
        SUM(oi.PRICE) AS revenue
    FROM OLIST_DW.MART.CLEAN_ORDER_ITEMS oi
    JOIN OLIST_DW.MART.DIM_PRODUCTS dp
        ON oi.PRODUCT_ID = dp.PRODUCT_ID
    GROUP BY dp.PRODUCT_CATEGORY_NAME
)

SELECT *,
       RANK() OVER (
           ORDER BY revenue DESC
       ) AS category_rank
FROM category_revenue;


-- =========================================================
-- BUSINESS QUESTION 10
-- Which product categories sell the most units?
-- =========================================================

SELECT
    dp.PRODUCT_CATEGORY_NAME,
    COUNT(*) AS UNITS_SOLD
FROM OLIST_DW.MART.CLEAN_ORDER_ITEMS oi
JOIN OLIST_DW.MART.DIM_PRODUCTS dp
    ON oi.PRODUCT_ID = dp.PRODUCT_ID
GROUP BY dp.PRODUCT_CATEGORY_NAME
ORDER BY UNITS_SOLD DESC;


-- =========================================================
-- BUSINESS QUESTION 11
-- Which sellers generate the highest revenue?
-- =========================================================

SELECT
    oi.SELLER_ID,
    ROUND(SUM(oi.PRICE),2) AS REVENUE
FROM OLIST_DW.MART.CLEAN_ORDER_ITEMS oi
GROUP BY oi.SELLER_ID
ORDER BY REVENUE DESC
LIMIT 20;


-- =========================================================
-- BUSINESS QUESTION 12
-- Which states have the highest-performing sellers?
-- =========================================================

SELECT
    ds.SELLER_STATE,
    ROUND(SUM(oi.PRICE),2) AS REVENUE
FROM OLIST_DW.MART.CLEAN_ORDER_ITEMS oi
JOIN OLIST_DW.MART.DIM_SELLERS ds
    ON oi.SELLER_ID = ds.SELLER_ID
GROUP BY ds.SELLER_STATE
ORDER BY REVENUE DESC;


-- =========================================================
-- BUSINESS QUESTION 13
-- What is the average delivery time?
-- =========================================================

SELECT
    ROUND(AVG(DELIVERY_DAYS),2) AS AVG_DELIVERY_DAYS
FROM OLIST_DW.MART.FACT_ORDERS;



-- =========================================================
-- BUSINESS QUESTION 14
-- How many orders were delivered late?
-- =========================================================

SELECT
    COUNT(*) AS LATE_ORDERS
FROM OLIST_DW.MART.FACT_ORDERS
WHERE DELIVERY_DELAY_DAYS > 0;


-- =========================================================
-- BUSINESS QUESTION 15
-- What is the average customer review score?
-- =========================================================

SELECT
    ROUND(AVG(REVIEW_SCORE),2) AS AVG_REVIEW_SCORE
FROM OLIST_DW.MART.FACT_REVIEWS;



-- =========================================================
-- BUSINESS QUESTION 16
-- How are customer reviews distributed?
-- =========================================================

SELECT
    REVIEW_CATEGORY,
    COUNT(*) AS REVIEWS
FROM OLIST_DW.MART.FACT_REVIEWS
GROUP BY REVIEW_CATEGORY
ORDER BY REVIEWS DESC;



-- =========================================================
-- BUSINESS QUESTION 17
-- Do delayed deliveries lead to poor reviews?
-- =========================================================

SELECT
    CASE
        WHEN fo.DELIVERY_DELAY_DAYS > 0
            THEN 'Late'
        ELSE 'On Time'
    END AS DELIVERY_STATUS,

    ROUND(AVG(fr.REVIEW_SCORE),2) AS AVG_REVIEW
FROM OLIST_DW.MART.FACT_ORDERS fo
JOIN OLIST_DW.MART.FACT_REVIEWS fr
    ON fo.ORDER_ID = fr.ORDER_ID
GROUP BY DELIVERY_STATUS;



-- =========================================================
-- BUSINESS QUESTION 18
-- What percentage of product value is freight cost?
-- =========================================================

SELECT
    ROUND(AVG(FREIGHT_PERCENTAGE),2) AS AVG_FREIGHT_PERCENT
FROM OLIST_DW.MART.FE_ORDER_ITEMS;



-- =========================================================
-- BUSINESS QUESTION 19
-- Which payment methods are most popular?
-- =========================================================

SELECT
    PAYMENT_TYPE,
    COUNT(*) AS PAYMENTS
FROM OLIST_DW.MART.FACT_PAYMENTS
GROUP BY PAYMENT_TYPE
ORDER BY PAYMENTS DESC;



-- =========================================================
-- BUSINESS QUESTION 20
-- How do customers prefer to finance purchases?
-- =========================================================

SELECT
    PAYMENT_INSTALLMENTS,
    COUNT(*) AS PAYMENTS
FROM OLIST_DW.MART.FACT_PAYMENTS
GROUP BY PAYMENT_INSTALLMENTS
ORDER BY PAYMENT_INSTALLMENTS;





